import type { Property } from '../types/property';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Penthouse de Lujo en Altamira',
    description: 'Excepcional penthouse con vistas panorámicas de 360° sobre Caracas. Tres terrazas privadas, sala de estar doble altura, cocina gourmet de diseño italiano y acabados de mármol importado. Una obra maestra de la arquitectura residencial.',
    type: 'apartamento',
    operation: 'venta',
    price: 680000,
    currency: 'USD',
    location: { city: 'Caracas', zone: 'Altamira', address: 'Av. Luis Roche, Res. Torre Ámbar PH' },
    features: { bedrooms: 4, bathrooms: 4, parking: 3, area: 380 },
    amenities: ['3 Terrazas Privadas', 'Jacuzzi', 'Piscina del Edificio', 'Gimnasio', 'Concierge 24/7', 'Bodega de Vinos', 'Sala de Cine'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=900&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80',
    ],
    featured: true,
    available: true,
    contactPhone: '+58 412-800-0001',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '2',
    title: 'Residencia Privada en La Lagunita',
    description: 'Majestuosa residencia unifamiliar en el exclusivo Country Club de La Lagunita. Diseño contemporáneo con jardines tipo resort, cancha de tenis privada, spa y casa de huéspedes independiente. La máxima expresión del lujo residencial en Caracas.',
    type: 'casa',
    operation: 'venta',
    price: 1450000,
    currency: 'USD',
    location: { city: 'Caracas', zone: 'La Lagunita', address: 'Country Club La Lagunita, Sector C' },
    features: { bedrooms: 6, bathrooms: 7, parking: 5, area: 820 },
    amenities: ['Piscina Tipo Resort', 'Cancha de Tenis', 'Spa Privado', 'Casa de Huéspedes', 'Bodega', 'Cuarto de Servicio', 'Generador', 'Sistema de Seguridad'],
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&q=80',
      'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=900&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=900&q=80',
    ],
    featured: true,
    available: true,
    contactPhone: '+58 412-800-0002',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    title: 'Apartamento Ejecutivo en Las Mercedes',
    description: 'Elegante apartamento completamente renovado en el corazón de Las Mercedes. Interiorismo de diseñador, cocina abierta con isla, sistema de domótica y balcón con vista al Este. Amoblado con piezas de colección.',
    type: 'apartamento',
    operation: 'alquiler',
    price: 2200,
    currency: 'USD',
    location: { city: 'Caracas', zone: 'Las Mercedes', address: 'Calle París, Res. Grand Parc' },
    features: { bedrooms: 3, bathrooms: 2, parking: 1, area: 145 },
    amenities: ['Amoblado Premium', 'Domótica', 'Piscina', 'Gimnasio', 'Seguridad 24/7', 'Área de Coworking'],
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=80',
    ],
    featured: true,
    available: true,
    contactPhone: '+58 412-800-0003',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '4',
    title: 'Oficina Corporativa en Chacao',
    description: 'Planta libre de 240m² en el corazón financiero de Caracas. Acabados de primera, sala de juntas con videoconferencia, recepción ejecutiva y 4 estacionamientos incluidos. Ideal para corporaciones internacionales.',
    type: 'oficina',
    operation: 'alquiler',
    price: 4800,
    currency: 'USD',
    location: { city: 'Caracas', zone: 'Chacao', address: 'Av. Francisco de Miranda, Torre Financiera' },
    features: { bedrooms: 0, bathrooms: 3, parking: 4, area: 240 },
    amenities: ['Sala de Juntas', 'Videoconferencia', 'Generador', 'Internet Fibra 1Gb', 'Aire Central', 'Recepción', 'Cafetería'],
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0004',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '5',
    title: 'Townhouse Moderno en Los Chorros',
    description: 'Elegante townhouse de tres plantas en urbanización privada de Los Chorros. Diseño minimalista con grandes ventanales, estudio privado, jardín con BBQ y acceso a piscina comunitaria olímpica.',
    type: 'casa',
    operation: 'alquiler',
    price: 3200,
    currency: 'USD',
    location: { city: 'Caracas', zone: 'Los Chorros', address: 'Urb. Los Chorros, Villas del Este, TH-8' },
    features: { bedrooms: 4, bathrooms: 3, parking: 2, area: 290 },
    amenities: ['Jardín Privado', 'BBQ', 'Estudio', 'Piscina Olímpica', 'Cancha de Padel', 'Seguridad Privada', 'Planta Eléctrica'],
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80',
      'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=900&q=80',
    ],
    featured: true,
    available: true,
    contactPhone: '+58 412-800-0005',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '6',
    title: 'Apartamento en El Rosal',
    description: 'Moderno apartamento en edificio boutique de El Rosal, a pasos de los mejores restaurantes y centros de negocios. Semi-amoblado, con acabados de diseñador y balcón privado.',
    type: 'apartamento',
    operation: 'alquiler',
    price: 1400,
    currency: 'USD',
    location: { city: 'Caracas', zone: 'El Rosal', address: 'Calle La Guairita, Res. Atrium' },
    features: { bedrooms: 2, bathrooms: 2, parking: 1, area: 110 },
    amenities: ['Semi-Amoblado', 'Balcón', 'Planta Eléctrica', 'Agua 24/7', 'Seguridad', 'Área Social'],
    images: [
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=900&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0006',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: '7',
    title: 'Casa en Trigal Norte, Valencia',
    description: 'Amplia residencia familiar en la mejor zona de Valencia. Cuatro habitaciones, sala-comedor de doble puntal, cocina remodelada y patio trasero con zona de BBQ y jardín. Urbanización cerrada con garita.',
    type: 'casa',
    operation: 'venta',
    price: 220000,
    currency: 'USD',
    location: { city: 'Valencia', zone: 'Trigal Norte', address: 'Urb. Trigal Norte, Calle 6, Casa 18' },
    features: { bedrooms: 4, bathrooms: 3, parking: 2, area: 310 },
    amenities: ['Jardín', 'BBQ', 'Garita', 'Depósito', 'Cuarto de Servicio', 'Portón Eléctrico'],
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0007',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '8',
    title: 'Apartamento con Vista al Mar en Lecherías',
    description: 'Exclusivo apartamento frente al mar en el boulevard de Lecherías. Vistas espectaculares al Caribe desde todos los ambientes, totalmente equipado y amoblado. El refugio ideal en el Oriente venezolano.',
    type: 'apartamento',
    operation: 'venta',
    price: 195000,
    currency: 'USD',
    location: { city: 'Barcelona', zone: 'Lecherías', address: 'Blvd. Naiguatá, Res. Cielo Mar' },
    features: { bedrooms: 3, bathrooms: 2, parking: 1, area: 130 },
    amenities: ['Vista al Mar', 'Piscina Infinity', 'Playa Privada', 'Amoblado', 'Seguridad 24/7', 'Área de BBQ'],
    images: [
      'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=900&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80',
    ],
    featured: true,
    available: true,
    contactPhone: '+58 412-800-0008',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '9',
    title: 'Local Gastronómico en Las Mercedes',
    description: 'Local de dos plantas en la zona gastronómica más exclusiva de Caracas. 180m² con cocina industrial equipada, barra, área de mesas para 60 cubiertos y terraza exterior. Ideal para restaurante fine dining.',
    type: 'local',
    operation: 'alquiler',
    price: 5500,
    currency: 'USD',
    location: { city: 'Caracas', zone: 'Las Mercedes', address: 'Av. Las Mercedes, entre Calle Madrid y New York' },
    features: { bedrooms: 0, bathrooms: 3, parking: 3, area: 180 },
    amenities: ['Cocina Industrial', 'Cámara Fría', 'Barra', 'Terraza', 'Almacén', 'Alto Tráfico Peatonal'],
    images: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0009',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: '10',
    title: 'Apartamento Nuevo en Barquisimeto',
    description: 'Estrenar en el desarrollo más moderno de Barquisimeto. Apartamento con acabados italianos, cocina integral Miele y sistema de domótica. Edificio con generador, cisterna y piscina panorámica en piso 20.',
    type: 'apartamento',
    operation: 'venta',
    price: 120000,
    currency: 'USD',
    location: { city: 'Barquisimeto', zone: 'El Pedregal', address: 'Av. Los Leones, Torre Bellagio, Piso 18' },
    features: { bedrooms: 3, bathrooms: 2, parking: 2, area: 135 },
    amenities: ['Domótica', 'Piscina Panorámica', 'Gimnasio', 'Sauna', 'Generador', 'Cisterna', 'Área Infantil'],
    images: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=900&q=80',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0010',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: '11',
    title: 'Casa Colonial Restaurada en El Hatillo',
    description: 'Joya arquitectónica en el corazón histórico de El Hatillo. Casa colonial completamente restaurada con materiales auténticos, patio central con fuente, bodega de vinos y moderna cocina integrada manteniendo la esencia colonial.',
    type: 'casa',
    operation: 'venta',
    price: 390000,
    currency: 'USD',
    location: { city: 'Caracas', zone: 'El Hatillo', address: 'Calle Real de El Hatillo, a 50m de la Plaza Bolívar' },
    features: { bedrooms: 4, bathrooms: 4, parking: 2, area: 350 },
    amenities: ['Patio Colonial', 'Fuente', 'Bodega de Vinos', 'Cocina Moderna', 'Jardín Trasero', 'Estudio'],
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=900&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
    ],
    featured: true,
    available: true,
    contactPhone: '+58 412-800-0011',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: '12',
    title: 'Terreno en Sebucán para Desarrollo',
    description: 'Terreno plano de 1,200m² en zona residencial premium de Sebucán. Topografía ideal, servicios disponibles y alta plusvalía. Certificado de Habitabilidad tramitable. Oportunidad única de inversión en el este de Caracas.',
    type: 'terreno',
    operation: 'venta',
    price: 480000,
    currency: 'USD',
    location: { city: 'Caracas', zone: 'Sebucán', address: 'Av. Principal de Sebucán' },
    features: { bedrooms: 0, bathrooms: 0, parking: 0, area: 1200 },
    amenities: ['Plano', 'Servicios Disponibles', 'Frente a Avenida', 'Alta Plusvalía', 'Cerca de Colegios'],
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80',
      'https://images.unsplash.com/photo-1488782565001-8d1e06ef7e70?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0012',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: '13',
    title: 'Apartamento Moderno en Prebo, Valencia',
    description: 'Luminoso apartamento en el exclusivo sector Prebo de Valencia. Remodelado totalmente, cocina abierta con granito, piso de porcelanato y balcón con vista a la ciudad. Edificio con generador y cisterna.',
    type: 'apartamento',
    operation: 'venta',
    price: 95000,
    currency: 'USD',
    location: { city: 'Valencia', zone: 'Prebo', address: 'Av. Bolívar Norte, Res. Torre Prebo, Piso 7' },
    features: { bedrooms: 3, bathrooms: 2, parking: 1, area: 115 },
    amenities: ['Balcón', 'Generador', 'Cisterna', 'Piscina', 'Área Social', 'Seguridad'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0013',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-01'),
  },
  {
    id: '14',
    title: 'Casa de Playa en Tucacas',
    description: 'Encantadora casa de playa a 50 metros del mar en Tucacas. Totalmente amoblada con terraza BBQ, ducha exterior y jardín tropical. Acceso directo a la playa y puerto de lanchas. Ideal como inversión vacacional.',
    type: 'casa',
    operation: 'venta',
    price: 165000,
    currency: 'USD',
    location: { city: 'Valencia', zone: 'Tucacas', address: 'Urb. Las Palmeras de Tucacas, Calle 3' },
    features: { bedrooms: 3, bathrooms: 2, parking: 2, area: 180 },
    amenities: ['Vista al Mar', 'Terraza BBQ', 'Amoblada', 'Jardín Tropical', 'Ducha Exterior', 'Puerto de Lanchas'],
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=900&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=900&q=80',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=900&q=80',
    ],
    featured: true,
    available: true,
    contactPhone: '+58 412-800-0014',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-05-10'),
  },
  {
    id: '15',
    title: 'Oficina Premium en Maracaibo',
    description: 'Planta libre de 180m² en la zona empresarial de Maracaibo. Acabados premium, sala de conferencias para 20 personas, recepción con aire central y 3 estacionamientos. Edificio clase A con seguridad 24/7.',
    type: 'oficina',
    operation: 'alquiler',
    price: 3200,
    currency: 'USD',
    location: { city: 'Maracaibo', zone: 'Las Mercedes (Maracaibo)', address: 'Av. 3H, Centro Empresarial del Lago, Piso 5' },
    features: { bedrooms: 0, bathrooms: 2, parking: 3, area: 180 },
    amenities: ['Sala de Conferencias', 'Aire Central', 'Generador', 'Internet Fibra', 'Recepción', 'Seguridad 24/7'],
    images: [
      'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=900&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0015',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: '16',
    title: 'Apartamento Ejecutivo en Maracaibo',
    description: 'Moderno apartamento en el corazón de Maracaibo, cerca del centro empresarial. Acabados de primera, cocina integral, sistema de seguridad y vista al lago. Ideal para ejecutivos y profesionales.',
    type: 'apartamento',
    operation: 'alquiler',
    price: 1100,
    currency: 'USD',
    location: { city: 'Maracaibo', zone: 'El Milagro', address: 'Av. El Milagro, Res. La Marina, Piso 12' },
    features: { bedrooms: 2, bathrooms: 2, parking: 1, area: 95 },
    amenities: ['Vista al Lago', 'Piscina', 'Gimnasio', 'Seguridad 24/7', 'Aire Central', 'Cisterna'],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0016',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: '17',
    title: 'Casa Campestre en Maracay',
    description: 'Hermosa casa en urbanización cerrada de Maracay con amplias áreas verdes. Cuatro habitaciones, sala familiar, cocina amplia, jardín de 600m² y piscina privada. Clima agradable todo el año.',
    type: 'casa',
    operation: 'venta',
    price: 280000,
    currency: 'USD',
    location: { city: 'Maracay', zone: 'Las Delicias', address: 'Urb. Las Delicias, Calle 2, Qta. El Jardín' },
    features: { bedrooms: 4, bathrooms: 3, parking: 3, area: 420 },
    amenities: ['Piscina Privada', 'Jardín 600m²', 'Generador', 'Depósito', 'Cuarto de Servicio', 'Garita', 'BBQ'],
    images: [
      'https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=900&q=80',
      'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=900&q=80',
      'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=900&q=80',
    ],
    featured: true,
    available: true,
    contactPhone: '+58 412-800-0017',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '18',
    title: 'Local Comercial en Centro de Barquisimeto',
    description: 'Amplio local de 320m² en el centro comercial de mayor tráfico de Barquisimeto. Frente a avenida principal, vitrina panorámica, depósito y baños. Apto para retail, banco o cadena de restaurantes.',
    type: 'local',
    operation: 'alquiler',
    price: 4200,
    currency: 'USD',
    location: { city: 'Barquisimeto', zone: 'Centro', address: 'Av. 20 con Calle 30, Local 3' },
    features: { bedrooms: 0, bathrooms: 2, parking: 5, area: 320 },
    amenities: ['Vitrina Panorámica', 'Depósito', 'Alto Tráfico', 'Frente a Avenida', 'Aire Central'],
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80',
      'https://images.unsplash.com/photo-1613977257592-4a9a32f9141b?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0018',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: '19',
    title: 'Apartamento Vista al Mar en Puerto La Cruz',
    description: 'Exclusivo apartamento frente al Paseo Colón de Puerto La Cruz con vista directa al mar Caribe. Totalmente renovado, tres habitaciones, amplias terrazas y acceso a piscina comunitaria con vista panorámica.',
    type: 'apartamento',
    operation: 'venta',
    price: 210000,
    currency: 'USD',
    location: { city: 'Puerto La Cruz', zone: 'Paseo Colón', address: 'Paseo Colón, Res. Torre Mar, Piso 8' },
    features: { bedrooms: 3, bathrooms: 2, parking: 1, area: 140 },
    amenities: ['Vista al Mar', 'Terraza', 'Piscina', 'Playa a 2 min', 'Amoblado Parcial', 'Seguridad 24/7'],
    images: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=900&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80',
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=900&q=80',
    ],
    featured: true,
    available: true,
    contactPhone: '+58 412-800-0019',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: '20',
    title: 'Townhouse en Maturín con Piscina',
    description: 'Townhouse de dos plantas en exclusiva urbanización privada de Maturín. Diseño contemporáneo, acabados de lujo, patio privado con piscina y jacuzzi. Excelente oportunidad en la capital petrolera de Venezuela.',
    type: 'casa',
    operation: 'venta',
    price: 175000,
    currency: 'USD',
    location: { city: 'Maturín', zone: 'Punta Palma', address: 'Urb. Punta Palma, Townhouse 14' },
    features: { bedrooms: 4, bathrooms: 3, parking: 2, area: 260 },
    amenities: ['Piscina Privada', 'Jacuzzi', 'Patio Privado', 'Generador', 'Cisterna', 'Seguridad', 'BBQ'],
    images: [
      'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=900&q=80',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=900&q=80',
    ],
    featured: false,
    available: true,
    contactPhone: '+58 412-800-0020',
    contactEmail: 'info@inmobiliaria.com.ve',
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-20'),
  },
];
